# Generated by Django 4.1.3 on 2022-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(blank=True, default="", max_length=100)),
                ("modelo", models.CharField(blank=True, default="", max_length=100)),
                ("foto", models.ImageField(upload_to="")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                "ordering": ["valor"],
            },
        ),
    ]
