# Generated by Django 4.1.3 on 2022-12-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="ano",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
